/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import server.Server;

/**
 *
 * @author ognje
 */
public class ServerForm extends javax.swing.JFrame {

    Server server;

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        server = new Server();
        jLabel2.setText("pokreni me");
        jButtonZAUSTAVI.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonZAUSTAVI = new javax.swing.JButton();
        jButtonPOKRENI = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemDatabase = new javax.swing.JMenuItem();
        jMenuItemPort = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemViewDoctors = new javax.swing.JMenuItem();
        jMenuItemCreateDoctor = new javax.swing.JMenuItem();
        jMenuItemUpdateDoctor = new javax.swing.JMenuItem();
        jMenuItemDeleteDoctor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonZAUSTAVI.setText("ZAUSTAVI SERVER");
        jButtonZAUSTAVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZAUSTAVIActionPerformed(evt);
            }
        });

        jButtonPOKRENI.setText("POKRENI SERVER");
        jButtonPOKRENI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPOKRENIActionPerformed(evt);
            }
        });

        jLabel1.setText("Status");

        jLabel2.setText("jLabel2");

        jMenu1.setText("Config");

        jMenuItemDatabase.setText("Database");
        jMenuItemDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDatabaseActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemDatabase);

        jMenuItemPort.setText("Port");
        jMenuItemPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPortActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemPort);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manage Doctors");

        jMenuItemViewDoctors.setText("View Doctors");
        jMenu2.add(jMenuItemViewDoctors);

        jMenuItemCreateDoctor.setText("Create New Doctor");
        jMenu2.add(jMenuItemCreateDoctor);

        jMenuItemUpdateDoctor.setText("Update Doctor");
        jMenu2.add(jMenuItemUpdateDoctor);

        jMenuItemDeleteDoctor.setText("Delete Doctor");
        jMenu2.add(jMenuItemDeleteDoctor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPOKRENI)
                        .addGap(54, 54, 54)
                        .addComponent(jButtonZAUSTAVI)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPOKRENI)
                    .addComponent(jButtonZAUSTAVI))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZAUSTAVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZAUSTAVIActionPerformed
        // TODO add your handling code here:
        server.zaustaviServer();
        jLabel2.setText("SERVER ZAUSTAVLJEN");
        jButtonPOKRENI.setEnabled(true);
        jButtonZAUSTAVI.setEnabled(false);


    }//GEN-LAST:event_jButtonZAUSTAVIActionPerformed

    private void jMenuItemDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDatabaseActionPerformed
        DatabaseDialog databaseDialog = new DatabaseDialog(this, false);
        databaseDialog.setVisible(true);


    }//GEN-LAST:event_jMenuItemDatabaseActionPerformed

    private void jMenuItemPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPortActionPerformed
        PortDialog portDialog = new PortDialog(this, false);
        portDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemPortActionPerformed

    private void jButtonPOKRENIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPOKRENIActionPerformed

        server.start();
        jLabel2.setText("POKRENUT SERVER");
        jButtonPOKRENI.setEnabled(false);
        jButtonZAUSTAVI.setEnabled(true);
    }//GEN-LAST:event_jButtonPOKRENIActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPOKRENI;
    private javax.swing.JButton jButtonZAUSTAVI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCreateDoctor;
    private javax.swing.JMenuItem jMenuItemDatabase;
    private javax.swing.JMenuItem jMenuItemDeleteDoctor;
    private javax.swing.JMenuItem jMenuItemPort;
    private javax.swing.JMenuItem jMenuItemUpdateDoctor;
    private javax.swing.JMenuItem jMenuItemViewDoctors;
    // End of variables declaration//GEN-END:variables
}
