/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ognje
 */
public class IzmeniReceptForm extends javax.swing.JFrame {

    /**
     * Creates new form IzmeniReceptForm
     */
    public IzmeniReceptForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldDATUM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelRECEPT = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxDIJAGNOZA = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonAZURIRAJ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmeni Recept");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Izmeni recept:");

        jLabelRECEPT.setText("jLabel2");

        jLabel3.setText("Dijagnoza:");

        jComboBoxDIJAGNOZA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Povišena telesna temperatura (febrilnost)", "Povrede (posekotine, opekotine, modrice)", "Vakcinacija (reakcije na vakcine)", "Dehidracija kod dece", "Konjunktivitis", "Akutne respiratorne infekcije (prehlada, virusne infekcije)", "Streptokokna angina", "Upala uha (otitis media)", "Bronhitis i bronhiolitis", "Upala pluća (pneumonija)", "Alergijski rinitis", "Astma kod dece", "Gastroenteritis (stomačni virus)", "Ospice (morbili)", "Vodene boginje (varicella)", "Dečiji ekcem (atopijski dermatitis)", "Urinarna infekcija", "Karijes mlečnih i stalnih zuba", "Gingivitis kod dece", "Aftozni stomatitis", "Trauma zuba (udari, prelomi)", "Malokluzija (nepravilan zagrizaj)", "Kašnjenje u razvoju govora", "Dislalija (pogrešan izgovor glasova)", "Razvojna dizartrija", "Oštećenje sluha povezano sa govorom", "Mucanje (balbuties)", "Poremećaj pažnje i hiperaktivnost (ADHD)", "Anksioznost kod dece", "Poremećaji u ponašanju", "Problemi sa prilagođavanjem u školi", "Noćni strahovi i noćne more" }));

        jLabel4.setText("Datum izdavanja:");

        jLabel5.setText("( 1.1.2000 )");

        jButtonAZURIRAJ.setText("Azuriraj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelRECEPT)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAZURIRAJ, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addComponent(jTextFieldDATUM))
                    .addComponent(jComboBoxDIJAGNOZA, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRECEPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDIJAGNOZA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDATUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAZURIRAJ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAZURIRAJ;
    private javax.swing.JComboBox<String> jComboBoxDIJAGNOZA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelRECEPT;
    private javax.swing.JTextField jTextFieldDATUM;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonAZURIRAJ() {
        return jButtonAZURIRAJ;
    }

    public JComboBox<String> getjComboBoxDIJAGNOZA() {
        return jComboBoxDIJAGNOZA;
    }

    public JLabel getjLabelRECEPT() {
        return jLabelRECEPT;
    }

    public JTextField getjTextFieldDATUM() {
        return jTextFieldDATUM;
    }
    public void azurirajAddActionListener(ActionListener actionListener) {
        jButtonAZURIRAJ.addActionListener(actionListener);
    }
    

}
