/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domain.Dete;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author ognje
 */
public class PrikazObrazovanjaForm extends javax.swing.JFrame {

    /**
     * Creates new form PrikazObrazovanjaForm
     */
    public PrikazObrazovanjaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelOBRAZOVANJE = new javax.swing.JLabel();
        jLabelPRED1 = new javax.swing.JLabel();
        jLabelPRED2 = new javax.swing.JLabel();
        jLabelPRED3 = new javax.swing.JLabel();
        jButtonPREDOBRISI = new javax.swing.JButton();
        jButtonPREDAZURIRAJ = new javax.swing.JButton();
        jButtonKATEGORISIPREDSKOLSKO = new javax.swing.JButton();
        jButtonKATEGORISISKOLSKO = new javax.swing.JButton();
        jLabelSKO1 = new javax.swing.JLabel();
        jLabelSKO2 = new javax.swing.JLabel();
        jLabelSKO3 = new javax.swing.JLabel();
        jLabelSKO4 = new javax.swing.JLabel();
        jLabelSKO5 = new javax.swing.JLabel();
        jButtonSKOOBRISI = new javax.swing.JButton();
        jButtonSKOAZURIRAJ = new javax.swing.JButton();
        jComboBoxDECA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz obrazovanja dece");

        jLabel1.setText("Proveri obrazovanje za dete:");

        jLabelOBRAZOVANJE.setText("jLabel2");

        jLabelPRED1.setText("Predskolsko Dete:");

        jLabelPRED2.setText("Grupa:");

        jLabelPRED3.setText("jLabel4");

        jButtonPREDOBRISI.setText("OBRISI");

        jButtonPREDAZURIRAJ.setText("AZURIRAJ");

        jButtonKATEGORISIPREDSKOLSKO.setText("Oznaci dete kao predskolsko");

        jButtonKATEGORISISKOLSKO.setText("Oznaci dete kao skolsko");

        jLabelSKO1.setText("Skolsko Dete:");

        jLabelSKO2.setText("Razred:");

        jLabelSKO3.setText("jLabel4");

        jLabelSKO4.setText("Odeljenje:");

        jLabelSKO5.setText("jLabel6");

        jButtonSKOOBRISI.setText("OBRISI");

        jButtonSKOAZURIRAJ.setText("AZURIRAJ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPRED1)
                            .addComponent(jLabelPRED2)
                            .addComponent(jLabelPRED3)
                            .addComponent(jButtonPREDOBRISI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPREDAZURIRAJ, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDECA, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonKATEGORISIPREDSKOLSKO, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonKATEGORISISKOLSKO, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelSKO1)
                            .addGap(202, 202, 202)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSKO3)
                            .addComponent(jLabelSKO2)
                            .addComponent(jLabelSKO5)
                            .addComponent(jLabelSKO4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSKOOBRISI, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonSKOAZURIRAJ, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelOBRAZOVANJE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelOBRAZOVANJE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDECA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKATEGORISIPREDSKOLSKO)
                    .addComponent(jButtonKATEGORISISKOLSKO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPRED1)
                    .addComponent(jLabelSKO1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPRED2)
                    .addComponent(jLabelSKO2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPRED3)
                    .addComponent(jLabelSKO3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPREDOBRISI)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPREDAZURIRAJ))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSKO4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSKO5)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSKOOBRISI)
                    .addComponent(jButtonSKOAZURIRAJ))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKATEGORISIPREDSKOLSKO;
    private javax.swing.JButton jButtonKATEGORISISKOLSKO;
    private javax.swing.JButton jButtonPREDAZURIRAJ;
    private javax.swing.JButton jButtonPREDOBRISI;
    private javax.swing.JButton jButtonSKOAZURIRAJ;
    private javax.swing.JButton jButtonSKOOBRISI;
    private javax.swing.JComboBox<Dete> jComboBoxDECA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelOBRAZOVANJE;
    private javax.swing.JLabel jLabelPRED1;
    private javax.swing.JLabel jLabelPRED2;
    private javax.swing.JLabel jLabelPRED3;
    private javax.swing.JLabel jLabelSKO1;
    private javax.swing.JLabel jLabelSKO2;
    private javax.swing.JLabel jLabelSKO3;
    private javax.swing.JLabel jLabelSKO4;
    private javax.swing.JLabel jLabelSKO5;
    // End of variables declaration//GEN-END:variables

    
    public void addBtnKATEGORISIPREDSKOLSKOActionListener(ActionListener actionListener) {
        jButtonKATEGORISIPREDSKOLSKO.addActionListener(actionListener);
    }
    public void addBtnKATEGORISISKOLSKOActionListener(ActionListener actionListener) {
        jButtonKATEGORISISKOLSKO.addActionListener(actionListener);
    }
    public void addBtnPREDAZURIRAJActionListener(ActionListener actionListener) {
        jButtonPREDAZURIRAJ.addActionListener(actionListener);
    }
    public void addBtnPREDOBRISIActionListener(ActionListener actionListener) {
        jButtonPREDOBRISI.addActionListener(actionListener);
    }
    public void addBtnSKOAZURIRAJActionListener(ActionListener actionListener) {
        jButtonSKOAZURIRAJ.addActionListener(actionListener);
    }
    public void addBtnSKOOBRISIActionListener(ActionListener actionListener) {
        jButtonSKOOBRISI.addActionListener(actionListener);
    }
    public void addCmbDECAActionListener(ActionListener actionListener) {
        jComboBoxDECA.addActionListener(actionListener);
    }
    
    
    
    
    public JButton getjButtonKATEGORISIPREDSKOLSKO() {
        return jButtonKATEGORISIPREDSKOLSKO;
    }

    public void setjButtonKATEGORISIPREDSKOLSKO(JButton jButtonKATEGORISIPREDSKOLSKO) {
        this.jButtonKATEGORISIPREDSKOLSKO = jButtonKATEGORISIPREDSKOLSKO;
    }

    public JButton getjButtonKATEGORISISKOLSKO() {
        return jButtonKATEGORISISKOLSKO;
    }

    public void setjButtonKATEGORISISKOLSKO(JButton jButtonKATEGORISISKOLSKO) {
        this.jButtonKATEGORISISKOLSKO = jButtonKATEGORISISKOLSKO;
    }

    public JButton getjButtonPREDAZURIRAJ() {
        return jButtonPREDAZURIRAJ;
    }

    public void setjButtonPREDAZURIRAJ(JButton jButtonPREDAZURIRAJ) {
        this.jButtonPREDAZURIRAJ = jButtonPREDAZURIRAJ;
    }

    public JButton getjButtonPREDOBRISI() {
        return jButtonPREDOBRISI;
    }

    public void setjButtonPREDOBRISI(JButton jButtonPREDOBRISI) {
        this.jButtonPREDOBRISI = jButtonPREDOBRISI;
    }

    public JButton getjButtonSKOAZURIRAJ() {
        return jButtonSKOAZURIRAJ;
    }

    public void setjButtonSKOAZURIRAJ(JButton jButtonSKOAZURIRAJ) {
        this.jButtonSKOAZURIRAJ = jButtonSKOAZURIRAJ;
    }

    public JButton getjButtonSKOOBRISI() {
        return jButtonSKOOBRISI;
    }

    public void setjButtonSKOOBRISI(JButton jButtonSKOOBRISI) {
        this.jButtonSKOOBRISI = jButtonSKOOBRISI;
    }

    public JComboBox<Dete> getjComboBoxDECA() {
        return jComboBoxDECA;
    }

    public void setjComboBoxDECA(JComboBox<Dete> jComboBoxDECA) {
        this.jComboBoxDECA = jComboBoxDECA;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabelOBRAZOVANJE() {
        return jLabelOBRAZOVANJE;
    }

    public void setjLabelOBRAZOVANJE(JLabel jLabelOBRAZOVANJE) {
        this.jLabelOBRAZOVANJE = jLabelOBRAZOVANJE;
    }

    public JLabel getjLabelPRED1() {
        return jLabelPRED1;
    }

    public void setjLabelPRED1(JLabel jLabelPRED1) {
        this.jLabelPRED1 = jLabelPRED1;
    }

    public JLabel getjLabelPRED2() {
        return jLabelPRED2;
    }

    public void setjLabelPRED2(JLabel jLabelPRED2) {
        this.jLabelPRED2 = jLabelPRED2;
    }

    public JLabel getjLabelPRED3() {
        return jLabelPRED3;
    }

    public void setjLabelPRED3(JLabel jLabelPRED3) {
        this.jLabelPRED3 = jLabelPRED3;
    }

    public JLabel getjLabelSKO1() {
        return jLabelSKO1;
    }

    public void setjLabelSKO1(JLabel jLabelSKO1) {
        this.jLabelSKO1 = jLabelSKO1;
    }

    public JLabel getjLabelSKO2() {
        return jLabelSKO2;
    }

    public void setjLabelSKO2(JLabel jLabelSKO2) {
        this.jLabelSKO2 = jLabelSKO2;
    }

    public JLabel getjLabelSKO3() {
        return jLabelSKO3;
    }

    public void setjLabelSKO3(JLabel jLabelSKO3) {
        this.jLabelSKO3 = jLabelSKO3;
    }

    public JLabel getjLabelSKO4() {
        return jLabelSKO4;
    }

    public void setjLabelSKO4(JLabel jLabelSKO4) {
        this.jLabelSKO4 = jLabelSKO4;
    }

    public JLabel getjLabelSKO5() {
        return jLabelSKO5;
    }

    public void setjLabelSKO5(JLabel jLabelSKO5) {
        this.jLabelSKO5 = jLabelSKO5;
    }


}
