/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author ognje
 */
public class PrikazDeceForm extends javax.swing.JFrame {

    /**
     * Creates new form PrikazDeceForm
     */
    public PrikazDeceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDECA = new javax.swing.JTable();
        jButtonDELETE = new javax.swing.JButton();
        jButtonAZURIRAJ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIME = new javax.swing.JTextField();
        jButtonPRETRAZI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPREZIME = new javax.swing.JTextField();
        jTextFieldDATUMRODJENJA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonRESETUJ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prikaz dece");

        jTableDECA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDECA);

        jButtonDELETE.setText("OBRISI");

        jButtonAZURIRAJ.setText("AZURIRAJ");

        jLabel1.setText("ime");

        jButtonPRETRAZI.setText("pretrazi");

        jLabel2.setText("prezime");

        jLabel3.setText("datum rodjenja");

        jLabel4.setText("(1.1.2001)");

        jButtonRESETUJ.setText("resetuj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonDELETE)
                        .addGap(97, 97, 97)
                        .addComponent(jButtonAZURIRAJ))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldIME, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPREZIME, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldDATUMRODJENJA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPRETRAZI)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRESETUJ)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPREZIME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDATUMRODJENJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPRETRAZI)
                    .addComponent(jButtonRESETUJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDELETE)
                    .addComponent(jButtonAZURIRAJ))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAZURIRAJ;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JButton jButtonPRETRAZI;
    private javax.swing.JButton jButtonRESETUJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDECA;
    private javax.swing.JTextField jTextFieldDATUMRODJENJA;
    private javax.swing.JTextField jTextFieldIME;
    private javax.swing.JTextField jTextFieldPREZIME;
    // End of variables declaration//GEN-END:variables

    public JTable getjTableDECA() {
        return jTableDECA;
    }

    public JButton getjButtonDELETE() {
        return jButtonDELETE;
    }

    public void addBtnDELETEActionListener(ActionListener actionListener) {
        jButtonDELETE.addActionListener(actionListener);
    }

    public void addBtnAZURIRAJActionListener(ActionListener actionListener) {
        jButtonAZURIRAJ.addActionListener(actionListener);
    }

    public void addBtnPRETRAZIctionListener(ActionListener actionListener) {
        jButtonPRETRAZI.addActionListener(actionListener);
    }

    public void addBtnRESETUJctionListener(ActionListener actionListener) {
        jButtonRESETUJ.addActionListener(actionListener);
    }

    public JTextField getjTextFieldDATUMRODJENJA() {
        return jTextFieldDATUMRODJENJA;
    }

    public void setjTextFieldDATUMRODJENJA(JTextField jTextFieldDATUMRODJENJA) {
        this.jTextFieldDATUMRODJENJA = jTextFieldDATUMRODJENJA;
    }

    public JTextField getjTextFieldIME() {
        return jTextFieldIME;
    }

    public void setjTextFieldIME(JTextField jTextFieldIME) {
        this.jTextFieldIME = jTextFieldIME;
    }

    public JTextField getjTextFieldPREZIME() {
        return jTextFieldPREZIME;
    }

    public void setjTextFieldPREZIME(JTextField jTextFieldPREZIME) {
        this.jTextFieldPREZIME = jTextFieldPREZIME;
    }

}
