/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author ognje
 */
public class PrikazObrazovanjaForm extends javax.swing.JFrame {

    /**
     * Creates new form PrikazObrazovanjaForm
     */
    public PrikazObrazovanjaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelOBRAZOVANJE = new javax.swing.JLabel();
        jLabelPRED1 = new javax.swing.JLabel();
        jLabelPRED2 = new javax.swing.JLabel();
        jLabelPRED3 = new javax.swing.JLabel();
        jButtonPREDOBRISI = new javax.swing.JButton();
        jButtonPREDAZURIRAJ = new javax.swing.JButton();
        jButtonKATEGORISIPREDSKOLSKO = new javax.swing.JButton();
        jButtonKATEGORISISKOLSKO = new javax.swing.JButton();
        jLabelSKO1 = new javax.swing.JLabel();
        jLabelSKO2 = new javax.swing.JLabel();
        jLabelSKO3 = new javax.swing.JLabel();
        jLabelSKO4 = new javax.swing.JLabel();
        jLabelSKO5 = new javax.swing.JLabel();
        jButtonSKOOBRISI = new javax.swing.JButton();
        jButtonSKOAZURIRAJ = new javax.swing.JButton();
        jComboBoxDECA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proveri obrazovanje za dete:");

        jLabelOBRAZOVANJE.setText("jLabel2");

        jLabelPRED1.setText("Predskolsko Dete:");

        jLabelPRED2.setText("Grupa:");

        jLabelPRED3.setText("jLabel4");

        jButtonPREDOBRISI.setText("OBRISI");

        jButtonPREDAZURIRAJ.setText("AZURIRAJ");

        jButtonKATEGORISIPREDSKOLSKO.setText("Oznaci dete kao predskolsko");

        jButtonKATEGORISISKOLSKO.setText("Oznaci dete kao skolsko");

        jLabelSKO1.setText("Skolsko Dete:");

        jLabelSKO2.setText("Razred:");

        jLabelSKO3.setText("jLabel4");

        jLabelSKO4.setText("Odeljenje:");

        jLabelSKO5.setText("jLabel6");

        jButtonSKOOBRISI.setText("OBRISI");

        jButtonSKOAZURIRAJ.setText("AZURIRAJ");

        jComboBoxDECA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPRED1)
                            .addComponent(jLabelPRED2)
                            .addComponent(jLabelPRED3)
                            .addComponent(jButtonPREDOBRISI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPREDAZURIRAJ, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxDECA, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonKATEGORISIPREDSKOLSKO, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButtonKATEGORISISKOLSKO, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelSKO1)
                            .addGap(202, 202, 202)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSKO3)
                            .addComponent(jLabelSKO2)
                            .addComponent(jLabelSKO5)
                            .addComponent(jLabelSKO4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSKOOBRISI, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonSKOAZURIRAJ, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelOBRAZOVANJE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelOBRAZOVANJE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDECA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKATEGORISIPREDSKOLSKO)
                    .addComponent(jButtonKATEGORISISKOLSKO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPRED1)
                    .addComponent(jLabelSKO1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPRED2)
                    .addComponent(jLabelSKO2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPRED3)
                    .addComponent(jLabelSKO3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPREDOBRISI)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPREDAZURIRAJ))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSKO4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSKO5)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSKOOBRISI)
                    .addComponent(jButtonSKOAZURIRAJ))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrikazObrazovanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrikazObrazovanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrikazObrazovanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrikazObrazovanjaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrikazObrazovanjaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKATEGORISIPREDSKOLSKO;
    private javax.swing.JButton jButtonKATEGORISISKOLSKO;
    private javax.swing.JButton jButtonPREDAZURIRAJ;
    private javax.swing.JButton jButtonPREDOBRISI;
    private javax.swing.JButton jButtonSKOAZURIRAJ;
    private javax.swing.JButton jButtonSKOOBRISI;
    private javax.swing.JComboBox<String> jComboBoxDECA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelOBRAZOVANJE;
    private javax.swing.JLabel jLabelPRED1;
    private javax.swing.JLabel jLabelPRED2;
    private javax.swing.JLabel jLabelPRED3;
    private javax.swing.JLabel jLabelSKO1;
    private javax.swing.JLabel jLabelSKO2;
    private javax.swing.JLabel jLabelSKO3;
    private javax.swing.JLabel jLabelSKO4;
    private javax.swing.JLabel jLabelSKO5;
    // End of variables declaration//GEN-END:variables
}
