/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ognje
 */
public class DodajLekForm extends javax.swing.JFrame {

    /**
     * Creates new form DodajLekForm
     */
    public DodajLekForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNAZIV = new javax.swing.JTextField();
        jTextFieldPROIZVODJAC = new javax.swing.JTextField();
        jButtonDODAJ = new javax.swing.JButton();
        jButtonAZURIRAJ = new javax.swing.JButton();
        jLabelID1 = new javax.swing.JLabel();
        jLabelID2 = new javax.swing.JLabel();
        jTextFieldINN = new javax.swing.JTextField();
        jTextFieldATCKLASIFIKACIJA = new javax.swing.JTextField();
        jTextFieldFARMAKOLOSKA = new javax.swing.JTextField();
        jTextFieldFARMACEUTSKIOBLIK = new javax.swing.JTextField();
        jTextFieldSADRZAJAKTIVNESUPSTANCE = new javax.swing.JTextField();
        jTextFieldPAKOVANJE = new javax.swing.JTextField();
        jTextFieldTERAPIJSKAGRUPA = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lek");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 550));
        setMinimumSize(new java.awt.Dimension(900, 550));
        setPreferredSize(new java.awt.Dimension(900, 550));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jTextFieldNAZIV);
        jTextFieldNAZIV.setBounds(30, 80, 170, 22);
        getContentPane().add(jTextFieldPROIZVODJAC);
        jTextFieldPROIZVODJAC.setBounds(200, 80, 180, 22);

        jButtonDODAJ.setText("DODAJ");
        jButtonDODAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDODAJActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDODAJ);
        jButtonDODAJ.setBounds(720, 360, 130, 70);

        jButtonAZURIRAJ.setText("AZURIRAJ");
        getContentPane().add(jButtonAZURIRAJ);
        jButtonAZURIRAJ.setBounds(580, 360, 130, 70);

        jLabelID1.setText("Id za azuriranje:");
        getContentPane().add(jLabelID1);
        jLabelID1.setBounds(380, 410, 81, 16);

        jLabelID2.setText("jLabel6");
        getContentPane().add(jLabelID2);
        jLabelID2.setBounds(480, 410, 37, 16);
        getContentPane().add(jTextFieldINN);
        jTextFieldINN.setBounds(30, 150, 220, 22);
        getContentPane().add(jTextFieldATCKLASIFIKACIJA);
        jTextFieldATCKLASIFIKACIJA.setBounds(250, 150, 100, 22);
        getContentPane().add(jTextFieldFARMAKOLOSKA);
        jTextFieldFARMAKOLOSKA.setBounds(30, 190, 310, 22);
        getContentPane().add(jTextFieldFARMACEUTSKIOBLIK);
        jTextFieldFARMACEUTSKIOBLIK.setBounds(80, 240, 160, 22);
        getContentPane().add(jTextFieldSADRZAJAKTIVNESUPSTANCE);
        jTextFieldSADRZAJAKTIVNESUPSTANCE.setBounds(270, 240, 100, 22);
        getContentPane().add(jTextFieldPAKOVANJE);
        jTextFieldPAKOVANJE.setBounds(390, 240, 140, 22);
        getContentPane().add(jTextFieldTERAPIJSKAGRUPA);
        jTextFieldTERAPIJSKAGRUPA.setBounds(530, 150, 120, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forms/lek.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 880, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDODAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDODAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDODAJActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAZURIRAJ;
    private javax.swing.JButton jButtonDODAJ;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelID2;
    private javax.swing.JTextField jTextFieldATCKLASIFIKACIJA;
    private javax.swing.JTextField jTextFieldFARMACEUTSKIOBLIK;
    private javax.swing.JTextField jTextFieldFARMAKOLOSKA;
    private javax.swing.JTextField jTextFieldINN;
    private javax.swing.JTextField jTextFieldNAZIV;
    private javax.swing.JTextField jTextFieldPAKOVANJE;
    private javax.swing.JTextField jTextFieldPROIZVODJAC;
    private javax.swing.JTextField jTextFieldSADRZAJAKTIVNESUPSTANCE;
    private javax.swing.JTextField jTextFieldTERAPIJSKAGRUPA;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonAZURIRAJ() {
        return jButtonAZURIRAJ;
    }

    public JButton getjButtonDODAJ() {
        return jButtonDODAJ;
    }

    public JLabel getjLabelID1() {
        return jLabelID1;
    }

    public JLabel getjLabelID2() {
        return jLabelID2;
    }

    public JTextField getjTextFieldNAZIV() {
        return jTextFieldNAZIV;
    }

    public JTextField getjTextFieldPROIZVODJAC() {
        return jTextFieldPROIZVODJAC;
    }

    public void dodajAddActionListener(ActionListener a) {
        jButtonDODAJ.addActionListener(a);
    }
    public void azurirajAddActionListener(ActionListener a) {
        jButtonAZURIRAJ.addActionListener(a);
    }

    public JTextField getjTextFieldATCKLASIFIKACIJA() {
        return jTextFieldATCKLASIFIKACIJA;
    }

    public JTextField getjTextFieldFARMACEUTSKIOBLIK() {
        return jTextFieldFARMACEUTSKIOBLIK;
    }

    public JTextField getjTextFieldFARMAKOLOSKA() {
        return jTextFieldFARMAKOLOSKA;
    }

    public JTextField getjTextFieldINN() {
        return jTextFieldINN;
    }

    public JTextField getjTextFieldPAKOVANJE() {
        return jTextFieldPAKOVANJE;
    }

    public JTextField getjTextFieldSADRZAJAKTIVNESUPSTANCE() {
        return jTextFieldSADRZAJAKTIVNESUPSTANCE;
    }

    public JTextField getjTextFieldTERAPIJSKAGRUPA() {
        return jTextFieldTERAPIJSKAGRUPA;
    }
    
    

}
