/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ognje
 */
public class DodajLekForm extends javax.swing.JFrame {

    /**
     * Creates new form DodajLekForm
     */
    public DodajLekForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNAZIV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPROIZVODJAC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAKTIVNISASTOJAK = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFARMACEUTSKAGRUPA = new javax.swing.JTextField();
        jButtonDODAJ = new javax.swing.JButton();
        jButtonAZURIRAJ = new javax.swing.JButton();
        jLabelID1 = new javax.swing.JLabel();
        jLabelID2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lek");

        jLabel1.setText("Naziv:");

        jLabel2.setText("Proizvodjac:");

        jLabel3.setText("Aktivni sastojak:");

        jLabel4.setText("Farmaceutska grupa");

        jButtonDODAJ.setText("Dodaj");
        jButtonDODAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDODAJActionPerformed(evt);
            }
        });

        jButtonAZURIRAJ.setText("Azuriraj");

        jLabelID1.setText("Id za azuriranje:");

        jLabelID2.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelID2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonAZURIRAJ)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                            .addComponent(jButtonDODAJ))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelID1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jTextFieldNAZIV, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addComponent(jTextFieldPROIZVODJAC)
                                .addComponent(jTextFieldAKTIVNISASTOJAK)
                                .addComponent(jTextFieldFARMACEUTSKAGRUPA)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelID1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelID2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNAZIV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldPROIZVODJAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldAKTIVNISASTOJAK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldFARMACEUTSKAGRUPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDODAJ)
                    .addComponent(jButtonAZURIRAJ))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDODAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDODAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDODAJActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAZURIRAJ;
    private javax.swing.JButton jButtonDODAJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelID2;
    private javax.swing.JTextField jTextFieldAKTIVNISASTOJAK;
    private javax.swing.JTextField jTextFieldFARMACEUTSKAGRUPA;
    private javax.swing.JTextField jTextFieldNAZIV;
    private javax.swing.JTextField jTextFieldPROIZVODJAC;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonAZURIRAJ() {
        return jButtonAZURIRAJ;
    }

    public JButton getjButtonDODAJ() {
        return jButtonDODAJ;
    }

    public JLabel getjLabelID1() {
        return jLabelID1;
    }

    public JLabel getjLabelID2() {
        return jLabelID2;
    }

    public JTextField getjTextFieldAKTIVNISASTOJAK() {
        return jTextFieldAKTIVNISASTOJAK;
    }

    public JTextField getjTextFieldFARMACEUTSKAGRUPA() {
        return jTextFieldFARMACEUTSKAGRUPA;
    }

    public JTextField getjTextFieldNAZIV() {
        return jTextFieldNAZIV;
    }

    public JTextField getjTextFieldPROIZVODJAC() {
        return jTextFieldPROIZVODJAC;
    }

    public void dodajAddActionListener(ActionListener a) {
        jButtonDODAJ.addActionListener(a);
    }
    public void azurirajAddActionListener(ActionListener a) {
        jButtonAZURIRAJ.addActionListener(a);
    }

}
