/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import domain.Specijalizacija;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
/**
 *
 * @author ognje
 */
public class PrikazDoktoraForm extends javax.swing.JFrame {

    /**
     * Creates new form PrikazDoktoraForm
     */
    public PrikazDoktoraForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDOKTORI = new javax.swing.JTable();
        jButtonDODAJ = new javax.swing.JButton();
        jButtonAZURIRAJ = new javax.swing.JButton();
        jButtonOBRISI = new javax.swing.JButton();
        jComboBoxSPECIJALIZACIJA = new javax.swing.JComboBox<>();
        jButtonDODAJSPECIJALIZACIJU = new javax.swing.JButton();
        jButtonOBRISISPECIJALIZACIJU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Doktori");

        jTableDOKTORI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableDOKTORI);

        jButtonDODAJ.setText("Dodaj");

        jButtonAZURIRAJ.setText("Azuriraj");

        jButtonOBRISI.setText("Obrisi");

        jButtonDODAJSPECIJALIZACIJU.setText("Specijalizuj");
        jButtonDODAJSPECIJALIZACIJU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDODAJSPECIJALIZACIJUActionPerformed(evt);
            }
        });

        jButtonOBRISISPECIJALIZACIJU.setText("Despecijalizuj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonDODAJ)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAZURIRAJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOBRISI))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxSPECIJALIZACIJA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDODAJSPECIJALIZACIJU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOBRISISPECIJALIZACIJU)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDODAJ)
                    .addComponent(jButtonAZURIRAJ)
                    .addComponent(jButtonOBRISI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxSPECIJALIZACIJA)
                        .addComponent(jButtonDODAJSPECIJALIZACIJU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonOBRISISPECIJALIZACIJU))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDODAJSPECIJALIZACIJUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDODAJSPECIJALIZACIJUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDODAJSPECIJALIZACIJUActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAZURIRAJ;
    private javax.swing.JButton jButtonDODAJ;
    private javax.swing.JButton jButtonDODAJSPECIJALIZACIJU;
    private javax.swing.JButton jButtonOBRISI;
    private javax.swing.JButton jButtonOBRISISPECIJALIZACIJU;
    private javax.swing.JComboBox<Specijalizacija> jComboBoxSPECIJALIZACIJA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDOKTORI;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonAZURIRAJ() {
        return jButtonAZURIRAJ;
    }

    public JButton getjButtonDODAJ() {
        return jButtonDODAJ;
    }

    public JButton getjButtonDODAJSPECIJALIZACIJU() {
        return jButtonDODAJSPECIJALIZACIJU;
    }

    public JButton getjButtonOBRISI() {
        return jButtonOBRISI;
    }

    public JButton getjButtonOBRISISPECIJALIZACIJU() {
        return jButtonOBRISISPECIJALIZACIJU;
    }

    public JComboBox<Specijalizacija> getjComboBoxSPECIJALIZACIJA() {
        return jComboBoxSPECIJALIZACIJA;
    }

    public JTable getjTableDOKTORI() {
        return jTableDOKTORI;
    }

    public void AZURIRAJaddActionListener(ActionListener a) {
        jButtonAZURIRAJ.addActionListener(a);
    }
    public void DODAJaddActionListener(ActionListener a) {
        jButtonDODAJ.addActionListener(a);
    }
    public void DODAJSPECIJALIZACIJUaddActionListener(ActionListener a) {
        jButtonDODAJSPECIJALIZACIJU.addActionListener(a);
    }
    public void OBRISIaddActionListener(ActionListener a) {
        jButtonOBRISI.addActionListener(a);
    }
    public void OBRISISPECIJALIZACIJUaddActionListener(ActionListener a) {
        jButtonOBRISISPECIJALIZACIJU.addActionListener(a);
    }



}
